### ISSUE TITLE
[BUG] `httpError: Connection was closed before full request has been made [ProtocolError]`

### ISSUE THREAD

**Issue by NightMachinary** [AmanoTeam/Unalix-nim#3]
```
echo 'https://practicalguidetoevil.wordpress.com/2021/06/11/interlude-north-iii/
https://practicalguidetoevil.wordpress.com/2021/06/15/interlude-west-ii/
https://practicalguidetoevil.wordpress.com/2021/06/18/interlude-east-iii/' | unalix -s
```

```
httpclient.nim(308)      httpError
Error: unhandled exception: Connection was closed before full request has been made [ProtocolError]
```

**Comment by NightMachinary** [comment]
Well, it seems `-s` was removed in the latest version, but I can't find its replacement. Is the functionality gone?

**Comment by SnwMds** [comment]
> Is the functionality gone?

Yeah, it's gone.

It was a poor implementation. My Nim skills are just mediocre at this time, so I can't make something good for now.

I plan to reimplement this at some point in the future.

**Comment by SnwMds** [comment]
Seems to be fixed in latest version. Can you check?

**Comment by NightMachinary** [comment]
@SnwMds Thanks, everything seems okay!
